export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const LOGOUT = 'LOGOUT';

export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_PENDING = 'FETCH_MOVIE_PENDING';
export const FETCH_MOVIE_FULFILLED = 'FETCH_MOVIE_FULFILLED';
export const FETCH_MOVIE_REJECTED = 'FETCH_MOVIE_REJECTED';

export const FETCH_SHOW = 'FETCH_SHOW';
export const FETCH_SHOW_PENDING = 'FETCH_SHOW_PENDING';
export const FETCH_SHOW_FULFILLED = 'FETCH_SHOW_FULFILLED';
export const FETCH_SHOW_REJECTED = 'FETCH_SHOW_REJECTED';

export const FETCH_SEASON = 'FETCH_SEASON';
export const FETCH_SEASON_PENDING = 'FETCH_SEASON_PENDING';
export const FETCH_SEASON_FULFILLED = 'FETCH_SEASON_FULFILLED';
export const FETCH_SEASON_REJECTED = 'FETCH_SEASON_REJECTED';

export const FETCH_EPISODE = 'FETCH_EPISODE';
export const FETCH_EPISODE_PENDING = 'FETCH_EPISODE_PENDING';
export const FETCH_EPISODE_FULFILLED = 'FETCH_EPISODE_FULFILLED';
export const FETCH_EPISODE_REJECTED = 'FETCH_EPISODE_REJECTED';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';

export const SEARCH = 'SEARCH';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED';
export const SEARCH_REJECTED = 'SEARCH_REJECTED';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const FETCH_ACCOUNT_PENDING = 'FETCH_ACCOUNT_PENDING';
export const FETCH_ACCOUNT_FULFILLED = 'FETCH_ACCOUNT_FULFILLED';
export const FETCH_ACCOUNT_REJECTED = 'FETCH_ACCOUNT_REJECTED';

export const USER_RATE_CHANGE = 'USER_RATE_CHANGE';
export const USER_RATE_CHANGE_PENDING = 'USER_RATE_CHANGE_PENDING';
export const USER_RATE_CHANGE_FULFILLED = 'USER_RATE_CHANGE_FULFILLED';
export const USER_RATE_CHANGE_REJECTED = 'USER_RATE_CHANGE_REJECTED';
