export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_MEDIA = 'FETCH_MEDIA';
export const FETCH_MEDIA_ERROR = 'FETCH_MEDIA_ERROR';
export const FETCH_MEDIA_ITEM = 'FETCH_MEDIA_ITEM';
export const FETCH_MEDIA_ITEM_ERROR = 'FETCH_MEDIA_ITEM_ERROR';
export const FETCH_MEDIA_ITEM_START = 'FETCH_MEDIA_ITEM_START';
