export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const LOGOUT = 'LOGOUT';
export const LOGGED_OUT = 'LOGGED_OUT';

export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_PENDING = 'FETCH_MOVIE_PENDING';
export const FETCH_MOVIE_FULFILLED = 'FETCH_MOVIE_FULFILLED';
export const FETCH_MOVIE_REJECTED = 'FETCH_MOVIE_REJECTED';

export const FETCH_SHOW = 'FETCH_SHOW';
export const FETCH_SHOW_PENDING = 'FETCH_SHOW_PENDING';
export const FETCH_SHOW_FULFILLED = 'FETCH_SHOW_FULFILLED';
export const FETCH_SHOW_REJECTED = 'FETCH_SHOW_REJECTED';

export const FETCH_SEASON = 'FETCH_SEASON';
export const FETCH_SEASON_PENDING = 'FETCH_SEASON_PENDING';
export const FETCH_SEASON_FULFILLED = 'FETCH_SEASON_FULFILLED';
export const FETCH_SEASON_REJECTED = 'FETCH_SEASON_REJECTED';

export const FETCH_EPISODE = 'FETCH_EPISODE';
export const FETCH_EPISODE_PENDING = 'FETCH_EPISODE_PENDING';
export const FETCH_EPISODE_FULFILLED = 'FETCH_EPISODE_FULFILLED';
export const FETCH_EPISODE_REJECTED = 'FETCH_EPISODE_REJECTED';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const FETCH_ACCOUNT_PENDING = 'FETCH_ACCOUNT_PENDING';
export const FETCH_ACCOUNT_FULFILLED = 'FETCH_ACCOUNT_FULFILLED';
export const FETCH_ACCOUNT_REJECTED = 'FETCH_ACCOUNT_REJECTED';

export const USER_RATE_CHANGE = 'USER_RATE_CHANGE';
export const USER_RATE_CHANGE_PENDING = 'USER_RATE_CHANGE_PENDING';
export const USER_RATE_CHANGE_FULFILLED = 'USER_RATE_CHANGE_FULFILLED';
export const USER_RATE_CHANGE_REJECTED = 'USER_RATE_CHANGE_REJECTED';

export const SUBSCRIBE_CHANGE = 'SUBSCRIBE_CHANGE';
export const SUBSCRIBE_CHANGE_PENDING = 'SUBSCRIBE_CHANGE_PENDING';
export const SUBSCRIBE_CHANGE_FULFILLED = 'SUBSCRIBE_CHANGE_FULFILLED';
export const SUBSCRIBE_CHANGE_REJECTED = 'SUBSCRIBE_CHANGE_REJECTED';

export const FETCH_USER_RATINGS = 'FETCH_USER_RATINGS';
export const FETCH_USER_RATINGS_FULFILLED = 'FETCH_USER_RATINGS_FULFILLED';
export const FETCH_USER_RATINGS_PENDING = 'FETCH_USER_RATINGS_PENDING';
export const FETCH_USER_RATINGS_REJECTED = 'FETCH_USER_RATINGS_REJECTED';

export const FETCH_USER_SUBSCRIPTIONS = 'FETCH_USER_SUBSCRIPTIONS';
export const FETCH_USER_SUBSCRIPTIONS_FULFILLED = 'FETCH_USER_SUBSCRIPTIONS_FULFILLED';
export const FETCH_USER_SUBSCRIPTIONS_PENDING = 'FETCH_USER_SUBSCRIPTIONS_PENDING';
export const FETCH_USER_SUBSCRIPTIONS_REJECTED = 'FETCH_USER_SUBSCRIPTIONS_REJECTED';

export const FETCH_ACTOR = 'FETCH_ACTOR';
export const FETCH_ACTOR_FULFILLED = 'FETCH_ACTOR_FULFILLED';
export const FETCH_ACTOR_PENDING = 'FETCH_ACTOR_PENDING';
export const FETCH_ACTOR_REJECTED = 'FETCH_ACTOR_REJECTED';

export const NEW_POST_INFO = 'NEW_POST_INFO';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED';
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_PENDING = 'LIKE_POST_PENDING';
export const LIKE_POST_REJECTED = 'LIKE_POST_REJECTED';
export const LIKE_POST_FULFILLED = 'LIKE_POST_FULFILLED';

export const FETCH_REPLIES = 'FETCH_REPLIES';
export const FETCH_REPLIES_PENDING = 'FETCH_REPLIES_PENDING';
export const FETCH_REPLIES_FULFILLED = 'FETCH_REPLIES_FULFILLED';
export const FETCH_REPLIES_REJECTED = 'FETCH_REPLIES_REJECTED';

export const FETCH_REPLY = 'FETCH_REPLY';
export const FETCH_REPLY_FULFILLED = 'FETCH_REPLY_FULFILLED';
